# Generated by Django 3.2 on 2022-10-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_provile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_provile',
            new_name='user_profile',
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_size',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
